# Routes
domain: 'https://baba-project.github.io/minel-jekyll-theme/'
url: 'https://baba-project.github.io/minel-jekyll-theme/'
assets_root: /assets/
assets_media: /assets/images/
permalink: '/:title/'
debug: false

# Publishing
future: false
show_drafts: false
keep_files: ['assets']
# Build settings
exclude:
  [
    'gulp_tasks',
    'api_data',
    '.ruby-version',
    '.editorconfig',
    'package.json',
    'package-lock.json',
    'gulpfile.babel.js',
    'README.md',
  ]
